version: "3.4"

services:
  db-service:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mydb:/var/lib/mysql

  user-service:
    build:
      context: ./tin-project-services/UserService
      dockerfile: Dockerfile
    ports:
      - "5001:80"

  product-service:
    build:
      context: ./tin-project-services/ProductService
      dockerfile: Dockerfile
    ports:
      - "5002:80"

  order-service:
    build:
      context: ./tin-project-services/OrderService
      dockerfile: Dockerfile
    ports:
      - "5003:80"

  orderdetails-service:
    build:
      context: ./tin-project-services/OrderDetailsService
      dockerfile: Dockerfile
    ports:
      - "5004:80"

  client-service:
    build:
      context: ./tin-project-services/ClientService
      dockerfile: Dockerfile
    ports:
      - "5005:80"

networks:
  default:
    driver: bridge

volumes:
  mydb:
